# Dockerfile para la aplicación Angular
FROM node:14 as build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build --prod

# Nginx para servir la aplicación Angular
FROM nginx:alpine
COPY --from=build /app/dist/torrefactora-tareas /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
